# UMH Core Configuration Example
# This file demonstrates how to configure UMH Core for the IoT Homelab setup
# Replace placeholder values with your actual environment settings

# MQTT Input - Subscribe to device data from your IoT stack
input:
  mqtt:
    client_id: YOUR_UNIQUE_CLIENT_ID
    topics:
      # Replace with your actual device topics
      - tele/YOUR_ORG/YOUR_SITE/tasmota/desk/SENSOR
      - tele/YOUR_ORG/YOUR_SITE/tasmota/siderack/SENSOR
      - tele/YOUR_ORG/YOUR_SITE/tasmota/cabinet/SENSOR
      # Add more topics as needed
    urls:
      - tcp://YOUR_PI_IP:1883

# InfluxDB Output Configuration - Store processed data
input:
  kafka:
    addresses:
      - localhost:9092  # UMH Core's internal Kafka
    client_id: tasmota_influx_benthos
    consumer_group: influxdb_consumer
    topics:
      - umh.messages

pipeline:
  processors:
    - bloblang: |-
        root = if metadata("kafka_key").contains("umh.v1.YOUR_ORG.YOUR_SITE") && metadata("kafka_key").contains("_historian") {
          "tasmota_sensors,topic=" + metadata("kafka_key") + " value=" + this.value.string() + " " + this.timestamp_ms.string()
        } else {
          deleted()
        }

output:
  http_client:
    batching:
      count: 1
    headers:
      Authorization: Token YOUR_INFLUX_TOKEN
      Content-Type: text/plain
    max_in_flight: 1
    retry_period: 1s
    timeout: 5s
    url: http://YOUR_PI_IP:8086/api/v2/write?org=YOUR_ORG&bucket=YOUR_BUCKET&precision=ms
    verb: POST

# Placeholder Values to Replace:
# YOUR_UNIQUE_CLIENT_ID    - e.g., 9e4e94d7-5b9e-4d3b-a92f-88d073d36b21
# YOUR_ORG                 - e.g., DKLP
# YOUR_SITE                - e.g., Office  
# YOUR_PI_IP               - e.g., 192.168.68.56
# YOUR_INFLUX_TOKEN        - Your InfluxDB access token
# YOUR_BUCKET              - e.g., dklp

# Network Setup Requirements:
# 1. Raspberry Pi MUST have fixed IP address
# 2. UMH Core runs on separate system
# 3. All connections use actual network IPs, never localhost
# 4. Tasmota devices publish to: tcp://YOUR_PI_IP:1883
# 5. UMH subscribes to: tcp://YOUR_PI_IP:1883
# 6. UMH writes to: http://YOUR_PI_IP:8086